- name: Task level variables
  hosts: local
  connection: local 
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: satya 
  tasks:
  - name: Print course intformation
    vars:
        COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }}, trainer is {{ TRAINER }}"


  - name: Print course intformation again
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, course duration is {{ DURATION }}, trainer is {{ TRAINER }}"

