- name: Task level variables
  hosts: local
  connection: local 
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: satya 
  tasks:
  - name: Print course intformation
    vars:
        COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hello ansible, course duration is 10HR, trainer is satya"

