 - name: variables preference
   hosts: local
   connection: local 
   vars:
    GREETING: "Hello from PLAY"
   vars_files:
   - course.yaml
   vars_prompt:
   - name: USERNAME
     prompt: Please enter your username
     private: true 

   tasks:
    name: print greetings
    vars:
      GREETING: "Hello from task"
    ansible.builtin.debug:
      msg: "{{GREETING}}"

  