- name: loops
  hosts: local 
  connection: local
  tasks:
  - name: print names using loops 
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
    - satya
    - bhargavi
    - manikanta 
    - devi 
